### PR TITLE
Added a Speaker module

### PR DESCRIPTION
**Pull request by DavidMansolino**
Added a Speaker module to play music files stored on the robot.
The speaker are not yet present on Webots.

### CODE REVIEW

**Comment by fabienrohrer** [comment]
We still don't simulate Microphones and Speakers in Webots.
Adding them would create a mismatch between the abilities of the simulated robot and the real robot.

I hesitate to include this "pull request".
Did you speak with Olivier about that?

**Comment by DavidMansolino** [comment]
Yes I spoke about that with him, and he told me that it would probably be added in a future version of webots, and suggest me to already add it to the wrapper in order to be ready (maybe with some minor modification) when speaker will be added to Webots.

**Comment by fabienrohrer** [comment]
Ok. I integrate it.

**Comment by omichel** [comment]
Hi,

Yes, we had a discussion on that topic and decided to implement a 
minimalist support for speakers (the idea is to invest a minimum of time 
in that) and we will see later how to change it when we support speakers 
and microphones in Webots.

In any case, don't spend too much time on this (and drop it if it 
appears to be too complex or causes problems).

-Olivier

**Pull request merged**
