### PR TITLE
Prepared the proto for robot window and remote control 

### PR DESCRIPTION
**Pull request by DavidMansolino**
Added fields robotWindow, showRobotWindow and remoteControl to the proto.

### CODE REVIEW

**Comment by fabienrohrer** [comment]
Hi David,

I'd say that hiding the robotWindow/remoteControl fields (don't putting them in the proto interface) would be better, because the 99% of users of this project won't be interested in modifying the robotWindow/remoteControl fields.
However it's good to open the showRobotWindow field.

The simplest following is that I reject this PR, do you agree?

Fabien

**Comment by DavidMansolino** [comment]
Hi Fabien,

Your are right, I will hide them,

For me it is simpler to correct this in this PR, 
but if for you it is simpler to reject it no problem I can do a new one.

David

**Comment by fabienrohrer** [comment]
Ok, so please correct it in the PR.

**Comment by DavidMansolino** [comment]
Done, 
I have let them empty for the moment,
I will fill them when I add the corresponding libraries.

**Pull request merged**
