### PR TITLE
Modified initial posture of the robot

### PR DESCRIPTION
**Pull request by DavidMansolino**
Modified initial posture of the robot to be the sit down position (on its knee) in simulation.

### CODE REVIEW

**Comment by fabienrohrer** [comment]
I'm sot sure about this commit because modifying the initial position is a very consequent modification.

**Comment by fabienrohrer** [comment]
I need more information to know if this is pertinent or not.
My point of view is currently that it's more convenient for the robot programming to start with position=0.
I'd say that modifying the rotation fields rather than the position fields is safer.

Why did you modify this?
Why did you choose the sit down position?

**Comment by DavidMansolino** [comment]
I chose the sit down position, because it is the position recomended to start the real robot (only position which is stable when the servos are off). So in the wrapper the start position is sit down. 

I didn't change the rotation field because the actual position 0 of the proto correspond to the 0 position of the real robot. 

Furthermore I think modifing the position field imply less adaptation to the controller (and manager) that modifing the rotation field.

But I agree with you that this is a very consequent modification.

**Comment by fabienrohrer** [comment]
I'm trying to list the pros and cons of this modification:

pros:
- it reduces the differences between a real setup and a simulated setup

cons:
- it breaks the strongly the backward compatibility
- it is specific to the motions of the Robotis framework

-> The backward compatibility can be broken if it's for a significant improvement (and it has been probably broken with some other modifications)
-> The dependency to the motions of the Robotis framework is however strong.

Ok, I think it's good to modify that..

**Pull request merged**
