### PR TITLE
Modified the Sample controller to run with the new Servo calibration

### PR DESCRIPTION
**Pull request by fabienrohrer**

### CODE REVIEW

**Comment by fabienrohrer** [comment]
After the Vitor modifications, the simulated DARwIn-OP was falling in the simulation.
I simply recalibrate the sample controller in order to improve the robustness of the robot behavior.

Moreover I observed that the motion reader function much more better. For example, the simulated robot is now able to stand up when it lays down. 
So I take the advantage of this to improve the sample in order to read the accelerometer values in order to detect the orientation of the robot and to play the motions to get up.

**Comment by fabienrohrer** [comment]
@darwinop: I have troubles with left and right kicks in simulation. The Robot is falling often.

http://www.youtube.com/watch?v=jd8uG1lrEOw

``` c++
if (x<0.0)
  mMotionManager->playPage(13); // left kick
else
  mMotionManager->playPage(12); // right kick
```

Do you think that a special motion page should be played before kicking?
Are pages 11 and 12 designed for that?

**Comment by darwinop** [comment]
i saw the video clip and i am perplexed on why he falls after a kick. 

the kicking motions are the exact same Robotis uses on their demo program and it works fine on the real  robot

**Comment by fabienrohrer** [comment]
Just before the kick motion, the robot is in a random state of the gait manager. Do I have to reset it in a more appropriated state before running the kick motion?

**Comment by darwinop** [comment]
no there is no need of resetting. the way the controller has the gait and motions (kicking, getting up) setup is technically fine.

However, the Robotis code has a few more aspects in the class libraries that help Darwin kick the ball more"effortlessly"

i.e. (head, action, walking independent of each other)
Head::GetInstance()->m_Joint.SetEnableHeadOnly(true, true)
Walking::GetInstance()->m_Joint.SetEnableBodyWithoutHead(true, true)
Action::GetInstance()->m_Joint.SetEnableBodyWithoutHead(true, true)

you'll notice that Action:: is independent of Head:: but Action:: is dependent on the status of Walking:: via a motion status.

by the way i should have brought this up long ago, but i think DarwinMotionManager should include classes for the head. The lack head can be seen when Darwin is ready to kick the ball by "him" looking straight.

**Comment by fabienrohrer** [comment]
@darwinop 

> no there is no need of resetting. the way the controller has the gait and motions (kicking, getting up) setup is technically fine.

So I think there is a problem of calibration. Maybe related with the bounding objects (or with the problem below). I'll check this ASAP.

> However, the Robotis code has a few more aspects in the class libraries that help Darwin kick the ball more"effortlessly"
> 
> i.e. (head, action, walking independent of each other)
> Head::GetInstance()->m_Joint.SetEnableHeadOnly(true, true)
> Walking::GetInstance()->m_Joint.SetEnableBodyWithoutHead(true, true)
> Action::GetInstance()->m_Joint.SetEnableBodyWithoutHead(true, true)
> 
> you'll notice that Action:: is independent of Head:: but Action:: is dependent on the status of Walking:: via a motion status.

I see. I didn't notice that the modules were so inter-dependent.

I will try to reformulate your comment in order to be sure that I understand well.

---

the user can use these DARwIn-OP features (both in reality and simulation / using exclusively the Webots API and the managers namespace):
1. set the servos positions using the Servo::setPosition()
2. play a motion (through a simple manager API)
3. play the gait (through a simple manager API)
4. actuate the leds
5. read all the sensors including camera, accelerometer and gyro

For points 1 to 3, it's possible to do that by initializing the DARwIn-OP framework like this:
Head::GetInstance()->m_Joint.SetEnableHeadOnly(true, true)
Walking::GetInstance()->m_Joint.SetEnableBodyWithoutHead(true, true)
Action::GetInstance()->m_Joint.SetEnableBodyWithoutHead(true, true)

## once for all.

Do you agree with that?
By a simple code snippet, could you tell me how to switch between the gait and the motion after this initialization?
After such kind of initialization, is it possible to set a servo manually? How (code snippet)?

I'm sure we are close to a nice result :-)

> by the way i should have brought this up long ago, but i think DarwinMotionManager should include classes for the head. The lack head can be seen when Darwin is ready to kick the ball by "him" looking straight.

Now, I think you're right.

**Comment by darwinop** [comment]
there's nothing wrong with the controller code. i simply think that the virtual darwin tends to bounce a bit too much relative to the real.
this is part of the main.cpp file located on /darwin/Linux/project/demo

perhaphs the look can help explain better. code switches between walking and action (kicking) depending on the ball tracker (with head involved). as explained above walking and action don't involve the head. see code after the break

about setting servos manually
I am not sure, but i assume it doesn't.

---

case SOCCER:
            if(Action::GetInstance()->IsRunning() == 0)
            {
                Head::GetInstance()->m_Joint.SetEnableHeadOnly(true, true);
                Walking::GetInstance()->m_Joint.SetEnableBodyWithoutHead(true, true);

```
            follower.Process(tracker.ball_position);

            if(follower.KickBall != 0)
            {
                Head::GetInstance()->m_Joint.SetEnableHeadOnly(true, true);
                Action::GetInstance()->m_Joint.SetEnableBodyWithoutHead(true, true);

                if(follower.KickBall == -1)
                {
                    Action::GetInstance()->Start(12);   // RIGHT KICK
                    fprintf(stderr, "RightKick! \n");
                }
                else if(follower.KickBall == 1)
                {
                    Action::GetInstance()->Start(13);   // LEFT KICK
                    fprintf(stderr, "LeftKick! \n");
                }
            }
            else
            {
                //have darwin turn until ball is found

                Head::GetInstance()->m_Joint.SetEnableHeadOnly(true, true);
                Action::GetInstance()->m_Joint.SetEnableBodyWithoutHead(true, true);

            }

        }
        break;
```

---

**Comment by fabienrohrer** [comment]
Thank you. I understand better now.

I still have two problems of comprehension:
- In the main loop of /darwin/Linux/project/demo, how the timing issues are dealed? I mean, it appears that this loop allows to perform the gait:

``` c++
Action::GetInstance()->m_Joint.SetEnableBody(true, true);
MotionManager::GetInstance()->SetEnable(true);
Walking::GetInstance()->m_Joint.SetEnableBodyWithoutHead(true, true);
while (true) {
  if(Action::GetInstance()->IsRunning() == 0 && event) {
    Action::GetInstance()->Start(12);
  }
}
```

-> But I don't see when the commands are sent, and why is there no sleeping statement. Is it multithreaded?
- Is it possible to stop the gait after its beginning without playing motion?

**Comment by darwinop** [comment]
Sorry for the non-response
I've been taking care of some more pressing work.

have you looked at the entire main code?

yes the code code runs multi-threaded (at least i believe because there has been some problems relating with multi-threading especially with the timer). 
I assume this is possible since the Atom chip has Intel's Hyper-threading enabled by default. i will test our own main code with hyper-threading off (however,i don't expect any differences). The Intel chip we use is the Atom Z530 and the PC setup is of a typical netbook

About stopping the gait
I am not sure if i will be able to answer, but given the way the code has been written i don't think so (stop the gait by itself).

**Pull request merged**
