### PR TITLE
Added a thread for the camera

### PR DESCRIPTION
**Pull request by DavidMansolino**
There is now a thread that continuously update the image taken by the camera.
The change in image format RGB -> BGRA will come after.
The functions camera::getWith and camera::getHeight have been improved.

### CODE REVIEW

**Comment by fabienrohrer** [comment]
Do you have good results with this way to proceed?

**Comment by DavidMansolino** [comment]
Quite good yes,
we reach the 30fps (we had 15-20fps before), which is the maximum of this camera.
However the main program is a little slowed down when the thread is active.

**Comment by fabienrohrer** [comment]
Very good ^^

And do you think double buffering will be required?

**Comment by DavidMansolino** [comment]
No I don't think,
I have made some test with the streamer (it permit to see the image taken by the camera in firefox),
and I have never seen any problem in the image.
Furthermore there is already a 'kind of' double buffering, the image is updated in ::Robot::LinuxCamera::GetInstance()->fbuffer->m_RGBFrame->m_ImageData and only when the update is finished it is copied in mImage (which is the buffer returned by Camera::getImage())

**Comment by fabienrohrer** [comment]
Ok, perfect.

Just an advise about the testing of this feature: the simplest way is to move the head while capturing images in order to have images which change a lot from one frame to another. Typical glitch would be that some images will be separated horizontally, the upper part would be the new frame and the lowest part the old frame.
If the image is stable, it could be difficult to see these glitches.

**Comment by DavidMansolino** [comment]
Thanks for your advise, I didn't move the head,
I moved my hand in front of the camera (which is more or less similar I think).
But I will do as you propose next time, I think your way is safer.

**Pull request merged**
